### ISSUE TITLE
Custom Forms?

### ISSUE THREAD

**Issue by davidlionel** [Zizaco/confide#130]
Hey, I'm still pretty new to Laravel.

I struggled (unsuccessfully) with user authentication for about 20 hours before discovering Confide. Confide hasn't given me any trouble whatsoever as far as set up.

You are a life saver.

I see in both the documentation and the confide config php that I can create custom forms to sign users in with Confide.

I know how to route it to a different view using the config, but could you please provide the syntax for how I should write my custom form in the actual view that I am now routing to? I know how to make forms, but I'm not quite sure how to tell it to work with confide?

Deepest apologies if this is already written somewhere and I missed it.

Thank you again,
David

**Comment by chriz74x** [comment]
I am trying to render a custom view but if I modify the config file with 'signup_form' => 'user.signup' and put the signup.blade.php file in the views/user folder the browser can't open the page, safari tells dropped  connection, chrome tells empty response...
