### ISSUE TITLE
syntax error, unexpected '' }}' when running "php artisan confide:migration"

### ISSUE THREAD

**Issue by tr33m4n** [Zizaco/confide#282]
Hello there,

Receiving this error when trying to create the confide migration:

PHP Parse error:  syntax error, unexpected '' }}' (T_CONSTANT_ENCAPSED_STRING) in /app/storage/views/97919f34d412715d58c30e6813e6b47e on line 15
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"syntax error, unexpected '' }}' (T_CONSTANT_ENCAPSED_STRING)","file":"\/app\/storage\/views\/97919f34d412715d58c30e6813e6b47e","line":15}}

Any ideas?

Cheers

**Comment by Shara96** [comment]
[Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '.1' (T_DNUMBER), expecting '{' how to solve this error

**Comment by Shara96** [comment]
I have been working wit laravel 5.1 and when I try to migrate the table in wamp server this error appears
how to solve?????
[Symfony\Component\Debug\Exception\FatalErrorException]
  syntax error, unexpected '.1' (T_DNUMBER), expecting '{'
