### ISSUE TITLE
Will creating a custom validator overrule the default validation class?

### ISSUE THREAD

**Issue by kedarv** [Zizaco/confide#348]
The docs were a bit unclear about this.
If I create a custom validator for my form, do I still need to validate the default inputs (email, username, etc.). Or do I only need to validate the custom fields that I have added on?

**Comment by DevHack** [comment]
See how you can override it :+1: 

```
<?php

use Zizaco\Confide\UserValidator as ConfideUserValidator;
use Zizaco\Confide\UserValidatorInterface;

class UserValidator extends ConfideUserValidator implements UserValidatorInterface
{
    public $rules = [
        'create' => [
            'username' => 'required',
            'email'    => 'required|email',
            'password' => 'required|min:4',
        ],
        'update' => [
            'username' => 'required',
            'email'    => 'required|email',
            'password' => 'required|min:4',
        ]
    ];
}
```

**Comment by Devmika** [comment]
How to use custom Validator including custom rules in controller class

**Comment by DevHack** [comment]
Just create custom class `UserValidator.php` in your model folder and copy paste above content.

**Comment by Devmika** [comment]
yes ... i did. but i don't know which method to be called to check validation pass or fail.

**Comment by DevHack** [comment]
```php
if($validation->fails()) {
    echo 'Jim! You failed-  Dough';
} else {
    echo 'Carrot! What a shot';
}
```

**Comment by Devmika** [comment]
Great! It works. thz for your answer.
