### ISSUE TITLE
Undefined index: driver

### ISSUE THREAD

**Issue by ganapathi-threesquare** [Zizaco/confide#390]
HI, i am using mongo and laravel but i dont know how to check the conn,,????

    protected function makeConnection($name)
    {
        $config = $this->getConfig($name);
        if (isset($this->extensions[$name])) {
            return call_user_func($this->extensions[$name], $config, $name);
        }
        $driver = $config['driver'];
        if (isset($this->extensions[$driver])) {
            return call_user_func($this->extensions[$driver], $config, $name);

**Comment by Zizaco** [comment]
For confide-mongo issues head up to https://github.com/Zizaco/confide-mongo
