### ISSUE TITLE
Make "username" truly optional

### ISSUE THREAD

**Issue by beckyresler** [Zizaco/confide#402]
After reviewing the functionality for Confide (with Entrust) and Sentry, I have decided to implement Confide in my application. However, I have been having issues getting it working properly.

I have absolutely no need for the "username" field in my application. Users will log in with their email addresses and first & last name fields will be used for personalization. Thus, I have not included the "username" column in my **users** table.

My first issue was encountered while attempting to create a user account. The **Zizaco\Confide\UserValidator::validateIsUnique()** function is setting the **$identity** array with BOTH email and username. This was causing an "undefined index : 'username"" error when the **Zizaco\Confide\EloquentRepository::getUserByIdentity()** function is called.

I got around this by creating my own custom validation class that extends the **UserValidator** class and replaces the **validateIsUnique()** function so that it only sets 'email' in the **$identity** array (in addition to updating the **$rules** array to match my fields).

My next issue ... one that I can't get around ... is the log in functionality.

In my **UserRepository** class, my **login()** function is calling `Confide::logAttempt($input, Config::get('confide::signup_confirm'))`.

**Zizaco\Confide\Confide::logAttempt()** eventually calls **Zizaco\Confide\EloquentRepository::getUserByEmailOrUsername()**, which sets BOTH email and username in the **$identity** array, and thus causes the "undefined index: 'username'" error again once the **Zizaco\Confide\EloquentRepository::getUserByIdentity()** function is called.

Why isn't there an optional parameter on the **Zizaco\Confide\Confide::logAttempt()** function where you can specify which field is the identity? I've seen mention of a 3rd parameter for this purpose in #32 & #34, but the code doesn't have that. And in #31 (from March **2013**), Zizaco agreed with prabhakarbhat that "username" should be optional. So why is it still not optional in September 2014? Am I missing something somewhere?

The ONLY way that I have been able to continue moving forward with the Confide integration in my app is by adding a "username" column to my **users** table. I feel like this is a hack and really don't want to add columns just for the sake of utilizing this package. And I REALLY want to use this package.

**Comment by Zizaco** [comment]
#419

**Comment by Nulimitz** [comment]
I was able to quickly solve the same issue with TimReynolds fix .. I just remarked out the line asking for the username as identity.

public function getUserByEmailOrUsername($emailOrUsername)
    {
        $identity = [
            'email' => $emailOrUsername,
            //'username' => $emailOrUsername
        ];

        return $this->getUserByIdentity($identity);
    }

the problem went away. I dint not include the switch -username in composer

**Comment by hizbul25** [comment]
Still i face this issue in login:

    SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause' (SQL:     select * from `users` where (`email` = test@something.com or `username` = test@something.com))

**Comment by m4r3x** [comment]
Can this be reopened and done properly?

Even on -optional branch problem still persists:
https://github.com/Zizaco/confide/blob/5f88717230d911aa26e7db8cc15a0cbd305fac22/src/Confide/EloquentRepository.php#L99

**Comment by z2z** [comment]
I agree with @m4r3x 

Best way to do this would be make it optional and  user identification field name defined in the config. As initially suggested by @wppd  https://github.com/Zizaco/confide/issues/402#issuecomment-56295661

Use case : use exisiting table with student_id as user identification field name.

**Comment by BlueManLine** [comment]
@m4r3x agree +1

**Comment by rrozanka** [comment]
@m4r3x ++
