### ISSUE TITLE
Confide::user() returning null

### ISSUE THREAD

**Issue by jjamaral** [Zizaco/confide#433]
Hi there!

I'm using Confide package in my Laravel 4 application, and i'm having some issues with login validation.

On my UsersController, my doLogin() function its working as expected.
if ($repo->login($input)) {
     return Redirect::intended('/');
}

But, on my login() function, it cant match this condition:
if (Confide::user()) { ... }

Any help please?

Thanks in advance!

**Comment by chaiha** [comment]
Did you find the way to solve this problem because I found a problem like you that Confide::user() return NULL by itself.
