### ISSUE TITLE
Validation And Soft Deletes

### ISSUE THREAD

**Issue by mcblum** [Zizaco/confide#436]
Thanks for your great work on this. When using soft deletes with users Confide's validator doesn't catch a repeat email or username because it seems to not be scanning the soft-deleted records. Any attempt to use the same email or username as a soft-deleted user results in the app crashing rather than an error message. Any idea how to fix that?

Thank you!
Matt

**Comment by Zizaco** [comment]
You're right. I'm gonna work on this.
Let's keep track of this issue here #449
