### ISSUE TITLE
Wrong confirmation code

### ISSUE THREAD

**Issue by jdeleonferreira** [Zizaco/confide#443]
I do this:
Route::get('/', function()
{
    $user = new User;
    $user->username = 'jdeleon';
    $user->email = 'xxxxxyyyyyyy@gmail.com';
    $user->password = 'foo_bar_1234';
    $user->password_confirmation = 'foo_bar_1234';
    $user->confirmation_code = md5(uniqid(mt_rand(), true));
    $user->save();
    echo '&lt;pre&gt;';
    var_dump($user->errors);
    echo '&lt;/pre&gt;';
}

obtain:

object(Illuminate\Support\MessageBag)#188 (2) {
  ["messages":protected]=>
  array(1) {
    ["password_confirmation"]=>
    array(1) {
      [0]=>
      string(24) "Wrong confirmation code."
    }
  }
  ["format":protected]=>
  string(8) ":message"
}

what is wrong?

**Comment by BhavinVisariya** [comment]
Any solution for wrong confirmation code? Plz post the same about why it is occurring and the solution as well.

Thanks
