### ISSUE TITLE
Extra where clause in log in time

### ISSUE THREAD

**Issue by sumanta-ghosh** [Zizaco/confide#447]
Is it possible to add  extra where clause in log in attempt. I add soft delete in users table and drop uniqueness from both field username and email and add extra field deleted_at for soft deleting . 
If I create a another row with same data and try to login then it's not working. So think I have to add one where clause deleted_at <> NULL . How to do that ?

**Comment by Zizaco** [comment]
Not in a easy way.
See #463 

But for soft deletion specifically (#449), confide should take care of it from out of the box.
