### ISSUE TITLE
logout and login, makes Confide::user() returns null

### ISSUE THREAD

**Issue by hyusetiawan** [Zizaco/confide#45]
the session is database and the following code returns Confide::user() as null

Confide::logAttempt(['email' => $user['email'], 'password' => $user['password']]);
Confide::logout();
Confide::logAttempt(['email' => $user['email'], 'password' => $user['password']]);
Confide::user(); //this returns null

**Comment by jgamao** [comment]
how to make new confide:migration to make new table in your database and use for the signup page in my application?
