### ISSUE TITLE
Line 58: Confide\CacheLoginThrottleService - error for isThrottled

### ISSUE THREAD

**Issue by diyriver** [Zizaco/confide#450]
Line 58 is currently:
```
$count = $this->countThrottle($identity, 0);
 ```
which sets the counting increment to 0 - thus it never counts up, and never throttles.

Should be changed to 
```
$count = $this->countThrottle($identity);  // use default increment of 1 to count up
```

**Comment by Zizaco** [comment]
@diyriver I understand your concern. But in line 58, the `isThrottled` method only checks if the user is throttled, it only calls `countThrottle` to **get** the current count. The actual increment occurs in: https://github.com/Zizaco/confide/blob/master/src/Confide/CacheLoginThrottleService.php#L43
That is called in `logAttempt`:
https://github.com/Zizaco/confide/blob/master/src/Confide/Confide.php#L127

:smiley:
