### ISSUE TITLE
Check reset token in Controller

### ISSUE THREAD

**Issue by Sloothword** [Zizaco/confide#451]
#70 adds the function to check for valid tokens to Confide.

But the generated Controller lacks exactly this check. Something like:
```
if(Confide::isValidToken($token)){
    return View::make(Config::get('confide::reset_password_form'))
        ->with('token', $token);
}else{
    return Redirect::to('login')
        ->withError(Lang::get('confide::confide.alerts.wrong_token'));
}
```

**Comment by Zizaco** [comment]
It checks if the token is valid in the **post** action.
But you can modify your controller to do that if you wish.
