### ISSUE TITLE
Custom field

### ISSUE THREAD

**Issue by hardikaecor** [Zizaco/confide#463]
Hi,
I need to add one more field for validation to my login attempt, apart from username and password. 
How can i do that?

Thanks
Hardik

**Comment by Zizaco** [comment]
Currently, this is not an easy task.

You will have to extend `Zizaco\Confide\Confide` in order to overwrite `logAttempt()`

Then, change this
```php
$user = $this->repo->getUserByEmailOrUsername($emailOrUsername);
```
to get the user using all the fields that you need.
