### ISSUE TITLE
Password Reset links displays even when token is Invalid

### ISSUE THREAD

**Issue by krokite** [Zizaco/confide#466]
I think, i missed doc, but when some one opens  http://laravel.local/users/reset_password/invalid_token_here , "New and Confirm" -> password reset box opens, though it does not reset password. But i think , this should check token before displaying box and if token is "Invalid", This should not open at all.

Thanks

**Comment by Zizaco** [comment]
Thats because the token is only checked in the **post** action. You can change the **get** action in your controller to check if the token exists first. It's an easy thing to do.

**Comment by krokite** [comment]
That is the worst thing. There should be validator on page " if "{confirmation_code}" exists in table, continue the page, else take him to login page... or better print an error "Invalid Code" without password reset box.
