### ISSUE TITLE
Maximum function nesting level reached while rendering custom log in view

### ISSUE THREAD

**Issue by rgbskills** [Zizaco/confide#468]
Error message:
Maximum function nesting level of '200' reached, aborting!

```
// app/config/packages/zizaco/confide/config.php 
'login_form' => 'user.login',
```
```
<!-- render code (login.blade.php)  -->
{{ Confide::makeLoginForm()->render() }}
```

version: 
"laravel/framework": "4.2.*",
"zizaco/confide": "~4.0@dev"

Did I find a bug or I'm not doing something correctly ?

**Comment by Zizaco** [comment]
Yes, you custom login view should not have `{{ Confide::makeLoginForm()->render() }}` (Which will render your custom login view again) inside of it.

The custom login view should be contain the actual input fields and not use confide to render it.
