### ISSUE TITLE
Make confide work together with fzaninotto's faker

### ISSUE THREAD

**Issue by krismp** [Zizaco/confide#473]
I can use **faker** with confide when seeding database, if only I remove the **ConfideUserInterface** implementation and **ConfideUser** trait. Do you have any plan in the future to make it work without having to remove them? But nice package btw. really love it, very helpful, thanks :)

**Comment by Zizaco** [comment]
I didn't get why you can't use faker. To me it seems that there would be no problem.

Can you demonstrate what are you trying to do?
