### ISSUE TITLE
How to make the username field not required without modifying the vendor package

### ISSUE THREAD

**Issue by 0x1AD2** [Zizaco/confide#475]
HI Zizaco,

How to make the username filed not required without modifying the vendor package, to be more specific how to completely remove the username field and only use the email field?

What I did in this case is I modified the 

UserValidator.php on line 44 to line 53

    public $rules = [
        'create' => [
            'email'    => 'required|email',
            'password' => 'required|min:4',
        ],
        'update' => [
            'email'    => 'required|email',
            'password' => 'required|min:4',
        ]
    ];

and on line 199 to line 122

```php
        $identity = [
            'email'    => $user->email,
        ];
```

And that's only for the registration part, If I ever run a composer update that code gets overwritten. And I read a part about creating your own validator but it's more then the validating part(correct me if I'm wrong).

**Comment by hotmeteor** [comment]
A patch that I committed was just merged, and it may solve your problem.

https://github.com/Zizaco/confide/commit/f00788879770d4a745312294c4988bb8973bce95

**Comment by andrewelkins** [comment]
Please let me know if it doesn't.

**Comment by graystevens** [comment]
Works fine for me here - changed my custom validator to no longer require username, and the same with my DB, allow null on username. Nicely done.
