### ISSUE TITLE
How about handling Sessions.

### ISSUE THREAD

**Issue by corientdev** [Zizaco/confide#476]
First of all thanks for this fantastic library.

And noq the question.
If I want to log off user after the inactivity of lets say 5 minutes then how can i achieve this?

I am interest to use laraauth along with confide and entrust

Please Guide me.

Thanks!

**Comment by Zizaco** [comment]
Every config that you do in Laravel authentication is used by Confide. So, you can use the `lifetime` of `config/session.php` to do that.
