### ISSUE TITLE
How to validate addtional fields and save part details to another table

### ISSUE THREAD

**Issue by donenvy** [Zizaco/confide#490]
Hi all,

I'm hoping someone can help as I have been pulling my hair out on this. Whilst this plugin works great out of the box. It seems making any customizations is a chore and half.

All I wanted to do was add some additonal fields, validate them and save one part to the users table and the other address fields to a different table.

I can't find any instruction on how to do this? Can anyone advise with an example?

**Comment by donenvy** [comment]
I've tried adding a customer validator, which when adding all the fileds to the $user object it all works ok. But as soon as I try and seperate it so one part goes to one table and one to the other, I get password_mismtach error

**Comment by rjp2525** [comment]
I'm having a similar issue, but not quite the same.. My issue is that if I attempt to add any sort of custom fields with custom validation and addition MySQL columns, I can't confirm the user no matter what. Not sure what's going on here, but Confide is not easily customizable I agree.

**Comment by donenvy** [comment]
I give up, this package is proving to be a pain in the butt to customize. Wish it was more user friendly, all these loops and holes you have to jump through just to add some columns into a different table at the time of validation, you can't intercept the override save function, to determine what should be saved and what needs to transfer across without modifying the vendor files, plus where is the documentation looks like not much exists for anything.

**Comment by Zizaco** [comment]
@donenvy I really didn't get what you were not able to do.

You want the `User` to [`HasMany`](http://laravel.com/docs/4.2/eloquent#one-to-many) Addresses? Why you coudn't make it? Can you show me your validator and your user model? (Then we may re-open this issue)
