### ISSUE TITLE
confide login form not parsing properly

### ISSUE THREAD

**Issue by pavankumar0440** [Zizaco/confide#501]
when going this location http://localhost:8000/users/login 
im getting like below image in browser
![screenshot from 2015-01-23 20 35 28](https://cloud.githubusercontent.com/assets/6078669/5876732/a299ace4-a33f-11e4-9698-ddf4da700816.png)

but when going to http://localhost:8000/users/create
it getting correctly
![screenshot from 2015-01-23 20 39 41](https://cloud.githubusercontent.com/assets/6078669/5876770/f5541514-a33f-11e4-89f5-a4144dfbfdbf.png)

**Comment by Zizaco** [comment]
Are you sure that your view filename ends with `.blade.php`?
