### ISSUE TITLE
Confide::user() return by itself.

### ISSUE THREAD

**Issue by chaiha** [Zizaco/confide#503]
I found the problem that when I log in to website by using Confide once and use the website for a while, Laravel show error that "Trying to get property of non-object" at the Confide::user(). How can I fix this problem? Thank you.
![confide](https://cloud.githubusercontent.com/assets/9088149/5887599/c5fda37a-a40c-11e4-817e-8469900bb86a.jpg)

**Comment by Zizaco** [comment]
Something like this should help.

```php
$user = Confide::user();

if ($user) {
    $username = $user->username;
} else {
    $username = 'Guest';
}
```
