### ISSUE TITLE
Laravel 5 Support?

### ISSUE THREAD

**Issue by LoveAndHappiness** [Zizaco/confide#528]
Does it work on Laravel 5?

**Comment by dominiquedutra** [comment]
Not out of the box.

https://github.com/Zizaco/confide/issues/448

**Comment by hopewise** [comment]
what about this fork: https://github.com/impleri/confide , when will they accept the pull request? it seems that its fixed to work with laravel 5

**Comment by gildniy** [comment]
Now the pull request was issued and is on 5.0.x dev version! Let's test this out and see what this can give!
